const Menu = [
    {
        id: 1,
        image: "images/aloo paratha.jpg",
        name: "Aloo Paratha",
        category: "Breakfast",
        price: "20$",
        description: "I love Aloo paratha Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolor quis ab, quo sint quod laudantium corporis distinctio id ducimus assumenda.",
    },
    {
        id: 2,
        image: "images/cholebhatura.jpg",
        name: "Chole bhatura",
        category: "Breakfast",
        price: "25₹",
        description: "I love Chole Bhatura Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolor quis ab, quo sint quod laudantium corporis distinctio id ducimus assumenda.",
    },
    {
        id: 3,
        image: "images/gujaratithali.jpg",
        name: "Veg Gujarati Thali",
        category: "Lunch",
        price: "25$",
        description: "I love Gujarati thali Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolor quis ab, quo sint quod laudantium corporis distinctio id ducimus assumenda.",
    },
    {
        id: 4,
        image: "images/maggi.jpg",
        name: "Maggi",
        category: "Breakfast",
        price: "5$",
        description: "I love Maggi Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolor quis ab, quo sint quod laudantium corporis distinctio id ducimus assumenda.",
    },
    {
        id: 5,
        image: "images/momos.jpg",
        name: "Veg Momos",
        category: "Breakfast",
        price: "25₹",
        description: "I love Momos Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolor quis ab, quo sint quod laudantium corporis distinctio id ducimus assumenda.",
    },
    {
        id: 6,
        image: "images/Pav-bhaji.jpg",
        name: "Pav bhaji",
        category: "Breakfast",
        price: "15$",
        description: "I love Pav bhaji Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolor quis ab, quo sint quod laudantium corporis distinctio id ducimus assumenda.",
    },
    {
        id: 7,
        image: "images/pizza.jpg",
        name: "Pizza",
        category: "Breakfast",
        price: "25₹",
        description: "I love Pizza Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolor quis ab, quo sint quod laudantium corporis distinctio id ducimus assumenda.",
    },
    {
        id: 8,
        image: "images/rajma-chawal.jpg",
        name: "Rajma chawal",
        category: "Dinner",
        price: "25₹",
        description: "I love Rajma chawal Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolor quis ab, quo sint quod laudantium corporis distinctio id ducimus assumenda.",
    },
    {
        id: 9,
        image: "images/samosa.jpg",
        name: "Samosa",
        category: "Evening",
        price: "25₹",
        description: "I love Samosa Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolor quis ab, quo sint quod laudantium corporis distinctio id ducimus assumenda.",
    },
    {
        id: 10,
        image: "images/samosa.jpg",
        name: "Jalebi Fafda",
        category: "Brunch",
        price: "25₹",
        description: "I love Jalebi Fafda Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolor quis ab, quo sint quod laudantium corporis distinctio id ducimus assumenda.",
    },

];

export default Menu;